.TH dumpauxv 1 2018-10-10
.SH NAME
dumpauxv \- dump auxv
.SH SYNOPSIS
.BR dumpauxv " [\fIauxv...\fP]"
.SH DESCRIPTION
.B dumpauxv
reads the files given as argument (or its standard output if none given) and
pretty print their content as if they were auxval array.
.PP
.in +2n
.EX
$ \fBdumpauxv /proc/self/auxv\fP
  SYSINFO_EHDR:   0x7ffe09774000
  HWCAP:  0xbfebfbff
  PAGESZ: 4096
  [...]
.EE
.in
.PP
